version: "3"

services:
  frontend:
    image: data-mining/frontend:latest
    container_name: frontend
    ports:
      - 4040:80
    # Uncomment to directly edit the frontend
    # volumes:
    #   - ./docker-images/frontend/app:/usr/share/nginx/html
    networks:
      - back-tier

  fishdb1:
    image: data-mining/fishdb1:latest
    container_name: fishdb1
    ports:
      - 4041:9090
    networks:
      - back-tier

  fishdb2:
    image: data-mining/fishdb2:latest
    container_name: fishdb2
    ports:
      - 4042:9090
    networks:
      - back-tier

  fishdb3:
    image: data-mining/fishdb3:latest
    container_name: fishdb3
    ports:
      - 4043:9090
    networks:
      - back-tier

  collector:
    image: data-mining/collector:latest
    container_name: collector
    networks:
      - back-tier

networks:
  back-tier:
